import "./globals.scss";
import Navbar from "./components/navbar/Navbar";
import { roboto } from "./ui/fonts";
export const metadata = {
  title: "Solana great Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
      {children}
      </body>
    </html>
  );
}
